### ISSUE TITLE
No result received on telegram

### ISSUE THREAD

**Issue by zidanb36912** [Stealerium/Stealerium#166]
![image](https://github.com/user-attachments/assets/4c265606-4c71-4c3b-9306-c98a4e9e7be1)
No result is received

**Comment by kgnfth** [comment]
If you have access to the target machine, build the stub in debug mode and rerun it on the target. After that, you can check the `Stealerium-Latest.log` file located at `C:\Users\USERNAME\AppData\Local\Temp` to view any error logs.

**Comment by zidanb36912** [comment]
Thank you sir for considering, I'll try that.

**Comment by zidanb36912** [comment]
`[2024-10-11 21:32:35.183] HideFile : Adding 'hidden' attribute to file C:\Users\Adam\AppData\Local\beb469ea8e67e34af4a3a18af80822a2
[2024-10-11 21:32:36.042] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-11 21:32:36.044] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-11 21:32:36.076] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-11 21:32:36.092] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-11 21:32:36.108] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-11 21:32:36.108] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-11 21:32:36.304] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-11 21:32:36.411] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-11 21:32:36.411] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-11 21:32:36.427] SelfDestruct: Initiating self-destruct procedure...
[2024-10-11 21:34:17.103] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-11 21:34:17.103] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-11 21:34:17.103] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-11 21:34:17.103] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-11 21:34:17.110] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-11 21:34:17.105] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-11 21:34:17.125] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-11 21:34:17.219] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-11 21:34:17.219] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-11 21:34:17.222] SelfDestruct: Initiating self-destruct procedure...
[2024-10-11 21:37:12.796] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-11 21:37:12.796] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-11 21:37:12.796] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-11 21:37:12.796] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-11 21:37:12.804] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-11 21:37:12.814] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-11 21:37:12.813] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-11 21:37:12.936] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-11 21:37:12.937] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-11 21:37:12.942] SelfDestruct: Initiating self-destruct procedure...
[2024-10-11 21:49:51.885] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-11 21:49:51.892] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-11 21:49:51.902] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-11 21:49:51.902] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-11 21:49:51.904] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-11 21:49:51.928] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-11 21:49:52.319] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-11 21:49:57.935] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-11 21:49:57.936] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-11 21:49:57.940] SelfDestruct: Initiating self-destruct procedure...
[2024-10-12 07:25:26.001] HideFile : Adding 'hidden' attribute to file C:\Users\Adam\AppData\Local\4090406004487e7a3874388da683f9cb
[2024-10-12 07:25:26.823] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-12 07:25:26.823] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-12 07:25:26.825] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-12 07:25:26.825] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-12 07:25:26.829] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-12 07:25:26.829] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-12 07:25:26.849] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-12 07:25:26.993] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-12 07:25:26.993] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-12 07:25:26.997] SelfDestruct: Initiating self-destruct procedure...
[2024-10-12 07:32:42.720] HideFile : Adding 'hidden' attribute to file C:\Users\Adam\AppData\Local\c8b7d21ab1d56a0d5917d39045db5ade
[2024-10-12 07:32:42.983] HideFile : Adding 'hidden' attribute to file C:\Users\Adam\Downloads\Newd.exe
[2024-10-12 07:32:42.985] StartDelay: Sleeping for 9.88 seconds.
[2024-10-12 07:32:58.606] Running passwords recovery...
[2024-10-12 07:32:58.665] Steam >> Application path not found in registry
[2024-10-12 07:32:58.668] Uplay >> Session not found
[2024-10-12 07:32:58.673] BattleNET >> Session not found
[2024-10-12 07:32:59.676] DesktopScreenshot >> Screenshot successfully created at: C:\Users\Adam\AppData\Local\c8b7d21ab1d56a0d5917d39045db5ade\Adam@DESKTOP-LTO070N_en-US\System\Desktop_20241012_073259.jpg
[2024-10-12 07:33:00.513] WebcamScreenshot : Camera screenshot failed.
System.Threading.ThreadStateException: Current thread must be set to single thread apartment (STA) mode before OLE calls can be made. Ensure that your Main function has STAThreadAttribute marked on it.
   at System.Windows.Forms.Clipboard.SetDataObject(Object data, Boolean copy, Int32 retryTimes, Int32 retryDelay)
   at Stealerium.Target.System.WebcamScreenshot.Make(String sSavePath)
[2024-10-12 07:33:03.652] Firefox >> Failed to recover data
System.ArgumentException: The UNC path should be of the form \\server\share.
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at Stealerium.Target.Browsers.Firefox.RecoverFirefox.Run(String sSavePath)
[2024-10-12 07:34:44.809] Report created successfully
[2024-10-12 07:57:50.131] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-12 07:57:50.131] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-12 07:57:50.134] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-12 07:57:50.152] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-12 07:57:50.162] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-12 07:57:50.163] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-12 07:57:50.174] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-12 07:57:52.484] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-12 07:57:52.484] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-12 07:57:52.487] SelfDestruct: Initiating self-destruct procedure...
HideFile : Adding 'hidden' attribute to file C:\Users\Adam\AppData\Local\0f54518052c145e4402dd59fbbf1a656
HideFile : Adding 'hidden' attribute to file C:\Users\Adam\Downloads\Stealerium-Release\Stealerium-Release\Binaries\Debug\
[2024-10-12 10:27:40.432] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-12 10:27:40.432] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-12 10:27:40.435] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-12 10:27:40.452] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-12 10:27:40.455] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-12 10:27:40.460] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-12 10:27:40.471] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-12 10:27:44.254] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-12 10:27:44.255] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-12 10:27:44.259] SelfDestruct: Initiating self-destruct procedure...
[2024-10-12 10:29:24.275] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-12 10:29:24.341] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-12 10:29:24.342] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-12 10:29:24.358] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-12 10:29:24.343] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-12 10:29:24.447] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-12 10:29:24.516] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-12 10:29:26.983] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-12 10:29:26.985] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-12 10:29:26.993] SelfDestruct: Initiating self-destruct procedure...
[2024-10-12 10:44:06.731] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-12 10:44:06.735] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-12 10:44:06.736] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-12 10:44:06.738] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-12 10:44:06.759] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-12 10:44:06.838] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-12 10:44:06.844] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-12 10:44:10.463] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-12 10:44:10.464] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-12 10:44:10.468] SelfDestruct: Initiating self-destruct procedure...
[2024-10-12 10:48:18.951] AntiAnalysis: Successfully loaded 'MachineGuids' list with 30 entries.
[2024-10-12 10:48:18.951] AntiAnalysis: Successfully loaded 'Services' list with 9 entries.
[2024-10-12 10:48:18.951] AntiAnalysis: Successfully loaded 'IPs' list with 203 entries.
[2024-10-12 10:48:18.951] AntiAnalysis: Successfully loaded 'GPUs' list with 99 entries.
[2024-10-12 10:48:18.960] AntiAnalysis: Successfully loaded 'PCNames' list with 230 entries.
[2024-10-12 10:48:18.955] AntiAnalysis: Successfully loaded 'Processes' list with 2 entries.
[2024-10-12 10:48:18.959] AntiAnalysis: Successfully loaded 'PCUsernames' list with 143 entries.
[2024-10-12 10:48:20.351] AntiAnalysis: Suspicious running service detected: VSS
[2024-10-12 10:48:20.352] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-12 10:48:20.355] SelfDestruct: Initiating self-destruct procedure...
[2024-10-12 12:49:00.089] HideFile : Adding 'hidden' attribute to file C:\Users\Adam\AppData\Local\52cae086041c216dcfa244043eabba75
[2024-10-12 12:49:00.341] HideFile : Adding 'hidden' attribute to file C:\Users\Adam\Downloads\build.exe
[2024-10-12 12:49:06.031] Running passwords recovery...
[2024-10-12 12:49:06.084] Steam >> Application path not found in registry
[2024-10-12 12:49:06.090] Uplay >> Session not found
[2024-10-12 12:49:06.098] BattleNET >> Session not found
[2024-10-12 12:49:06.428] DesktopScreenshot >> Screenshot successfully created at: C:\Users\Adam\AppData\Local\52cae086041c216dcfa244043eabba75\Adam@DESKTOP-LTO070N_en-US\System\Desktop_20241012_124906.jpg
[2024-10-12 12:49:09.161] Firefox >> Failed to recover data
System.ArgumentException: The UNC path should be of the form \\server\share.
   at System.IO.LongPathHelper.Normalize(String path, UInt32 maxPathLength, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at Stealerium.Target.Browsers.Firefox.RecoverFirefox.Run(String sSavePath)
`

**Comment by zidanb36912** [comment]
"[2024-10-12 10:48:20.352] AntiAnalysis: Suspicious service detected! Self-destructing...
[2024-10-12 10:48:20.355] SelfDestruct: Initiating self-destruct procedure...
" I see that it self destructed.

**Comment by zidanb36912** [comment]
I will rebuild again by removing the Self-destructing from source code

**Comment by kgnfth** [comment]
> I will rebuild again by removing the Self-destructing from source code

Just use the Builder.exe and build the file without Anti Analysis option checked.

**Comment by zidanb36912** [comment]
Alright let me try, but I had not actually tested this on a virtual machine I tested this on a windows 11 laptop.

**Comment by kgnfth** [comment]
> Alright let me try, but I had not actually tested this on a virtual machine I tested this on a windows 11 laptop.

Well one of the following services where detected:

- vmicheartbeat
- vmickvpexchange
- vmicrdv
- vmicshutdown
- vmictimesync
- vmicvss
- VmRemoteService
- VSS
- Sysmon64

**Comment by zidanb36912** [comment]
Ahhh I see the VmRemoteService was the problem I believe because I have Hyper V and kali on it running

**Comment by zidanb36912** [comment]
I will disable the Hyper V

**Comment by zidanb36912** [comment]
Also I will trun off Sandbox feature just in case

**Comment by kgnfth** [comment]
> Ahhh I see the VmRemoteService was the problem I believe because I have Hyper V and kali on it running

No its the VSS service as you can see in the log. VSS is enabled in Hyper V.

**Comment by zidanb36912** [comment]
Oh yes sir, I am going to disable hyper v, sandbox and vm feature and then try again.

**Comment by kgnfth** [comment]
> Reference

you dont need to disable them. Why dont u use the builder.exe or just set DebugMode to 0

**Comment by zidanb36912** [comment]
Umm sir how can I set DebugMode to 0 precisely? 
![Uploading Screenshot 2024-10-12 182104.png…]()

**Comment by kgnfth** [comment]
I dont see the picture. Are u using the source code, or the builder.exe?

**Comment by zidanb36912** [comment]
sir I am using the builder.exe

**Comment by kgnfth** [comment]
It should be like this unchecked
![image](https://github.com/user-attachments/assets/5e4f62a4-99d3-4ce7-bd64-0c1b57206b01)

**Comment by zidanb36912** [comment]
There is option Debug all exception file, use anti analyis, use random start delay etc

**Comment by zidanb36912** [comment]
I see cool

**Comment by zidanb36912** [comment]
Let me try

**Comment by zidanb36912** [comment]
![Screenshot 2024-10-12 183052](https://github.com/user-attachments/assets/03ced6d3-c564-4fc0-a803-94343528d154)

**Comment by zidanb36912** [comment]
![image](https://github.com/user-attachments/assets/e7e7f27f-a8ac-41eb-9f8b-f25f811ee394)
No log file I ran build.exe as administrator and without administrator twice

**Comment by zidanb36912** [comment]
![image](https://github.com/user-attachments/assets/84eed16c-e4cd-4dc7-b2ee-90120412186a)

**Comment by zidanb36912** [comment]
Nothing

**Comment by kgnfth** [comment]
Build it like this, to see the log file
![image](https://github.com/user-attachments/assets/a2cf12ad-4ccc-4502-ab42-017bef8777e7)

**Comment by zidanb36912** [comment]
Alright

**Comment by zidanb36912** [comment]
![image](https://github.com/user-attachments/assets/77995cd3-52da-415a-8779-5bcfd2ddba99)
AHHH it has self destructed

**Comment by zidanb36912** [comment]
VSS

**Comment by zidanb36912** [comment]
I need to get ride of VSS

**Comment by kgnfth** [comment]
Wait i will release a new build.

**Comment by zidanb36912** [comment]
Thank you very much sir!

**Comment by zidanb36912** [comment]
But you can tell me I can modify the code from my side.

**Comment by kgnfth** [comment]
> But you can tell me I can modify the code from my side.

Yea but its not like changing one line of code.

**Comment by zidanb36912** [comment]
Sir you are the expert you can handle this, I will wait.

**Comment by zidanb36912** [comment]
![image](https://github.com/user-attachments/assets/23ce81d5-a0bc-4159-aa3d-e446ea421796)
Sir I figured it is possible to disable VSS from services.

**Comment by zidanb36912** [comment]
But well this will not actually solve the problem

**Comment by zidanb36912** [comment]
Actual code needs to be crafted to handle such problems.

**Comment by zidanb36912** [comment]
It is working now I believe because I saw it downloading files from my dummy onedrive

**Comment by zidanb36912** [comment]
I am merely waiting for result to show up on telegram

**Comment by zidanb36912** [comment]
I am keeping track of the logs

**Comment by kgnfth** [comment]
> ![image](https://private-user-images.githubusercontent.com/184336944/375958189-23ce81d5-a0bc-4159-aa3d-e446ea421796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3Mzc0NTksIm5iZiI6MTcyODczNzE1OSwicGF0aCI6Ii8xODQzMzY5NDQvMzc1OTU4MTg5LTIzY2U4MWQ1LWEwYmMtNDE1OS1hYTNkLWU0NDZlYTQyMTc5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMjQ1NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWMxOTExYzNmZTRiYzUwYjA3YjI2MTA3NmE2YTkxMGI0ODVhYzUzYWU5MTM3OGI0OTE2MWZhZTczYTJhMTVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5s4aONG6gwDX9-0Yh2FdjE95R4zlqCOYyp3-yfRoAjs) Sir I figured it is possible to disable VSS from services.

You should not, its a coding issue. You can now use v3.5.2 https://github.com/Stealerium/Stealerium/releases/tag/v3.5.2

**Comment by zidanb36912** [comment]
Cool thank you sir. But after I disabled vss it works.

**Comment by kgnfth** [comment]
> Cool thank you sir. But after I disabled vss it works.

Great can i see the log ?

**Comment by zidanb36912** [comment]
![image](https://github.com/user-attachments/assets/5915a44f-c568-42bc-b94c-adaa26890ff7)
The size of file is big will take a while to be sent

**Comment by zidanb36912** [comment]
![image](https://github.com/user-attachments/assets/e6066af0-7e1d-467f-bd3f-ba736d5d19f4)
But I am wondering if it is stuck or something why is the bandwidth not high?

**Comment by kgnfth** [comment]
No idea, it has nothing to do with Stealerium

**Comment by zidanb36912** [comment]
Some user did report issue that they need to use vpn or proxies or else it does not works

**Comment by zidanb36912** [comment]
It is still stuck

**Comment by kgnfth** [comment]
> It is still stuck

If u can access https://gofile.io then there is nothing wrong, but if you cant access it, then you need to use vpn to access the url

**Comment by zidanb36912** [comment]
I can access it

**Comment by zidanb36912** [comment]
I did try to manually upload file on the site and was successful

**Comment by zidanb36912** [comment]
Let me only try keylogger and turn off grab file just to make sure it works

**Comment by zidanb36912** [comment]
![image](https://github.com/user-attachments/assets/cd450068-0b4f-49f2-844e-95be084abcd2)

**Comment by kgnfth** [comment]
Then there is nothing wrong. I cant help, without knowing the issue exactly.
 
Add me on telegram to discuss further. https://t.me/Teal_c

**Comment by zidanb36912** [comment]
Sure
